// flow-typed signature: 9e5e8ad5e6170f8ff934e6cf9f431318
// flow-typed version: <<STUB>>/babel-minify-webpack-plugin_v^0.2.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-minify-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-minify-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-minify-webpack-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'babel-minify-webpack-plugin/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-minify-webpack-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'babel-minify-webpack-plugin/dist/cjs'>;
}
declare module 'babel-minify-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'babel-minify-webpack-plugin/dist/index'>;
}
