// flow-typed signature: ad6eb26e0f77e3d3bf47957c6bc8e3c6
// flow-typed version: <<STUB>>/babel-plugin-universal-import_v^1.2.7/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-universal-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-universal-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-universal-import/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'babel-plugin-universal-import/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'babel-plugin-universal-import/importCss' {
  declare module.exports: any;
}

declare module 'babel-plugin-universal-import/universalImport' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-universal-import/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'babel-plugin-universal-import/coverage/lcov-report/prettify'>;
}
declare module 'babel-plugin-universal-import/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'babel-plugin-universal-import/coverage/lcov-report/sorter'>;
}
declare module 'babel-plugin-universal-import/importCss.js' {
  declare module.exports: $Exports<'babel-plugin-universal-import/importCss'>;
}
declare module 'babel-plugin-universal-import/index' {
  declare module.exports: $Exports<'babel-plugin-universal-import'>;
}
declare module 'babel-plugin-universal-import/index.js' {
  declare module.exports: $Exports<'babel-plugin-universal-import'>;
}
declare module 'babel-plugin-universal-import/universalImport.js' {
  declare module.exports: $Exports<'babel-plugin-universal-import/universalImport'>;
}
