// flow-typed signature: fc16da00c350f9fcbcaf88ef1c3a4c92
// flow-typed version: <<STUB>>/postcss-flexbugs-fixes_v^3.2.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-flexbugs-fixes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-flexbugs-fixes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-flexbugs-fixes/bugs/bug4' {
  declare module.exports: any;
}

declare module 'postcss-flexbugs-fixes/bugs/bug6' {
  declare module.exports: any;
}

declare module 'postcss-flexbugs-fixes/bugs/bug81a' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-flexbugs-fixes/bugs/bug4.js' {
  declare module.exports: $Exports<'postcss-flexbugs-fixes/bugs/bug4'>;
}
declare module 'postcss-flexbugs-fixes/bugs/bug6.js' {
  declare module.exports: $Exports<'postcss-flexbugs-fixes/bugs/bug6'>;
}
declare module 'postcss-flexbugs-fixes/bugs/bug81a.js' {
  declare module.exports: $Exports<'postcss-flexbugs-fixes/bugs/bug81a'>;
}
declare module 'postcss-flexbugs-fixes/index' {
  declare module.exports: $Exports<'postcss-flexbugs-fixes'>;
}
declare module 'postcss-flexbugs-fixes/index.js' {
  declare module.exports: $Exports<'postcss-flexbugs-fixes'>;
}
