// flow-typed signature: cdbf2202bb268bb0dc7e4ae544455726
// flow-typed version: <<STUB>>/write-file-webpack-plugin_v^4.2.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'write-file-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'write-file-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'write-file-webpack-plugin/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'write-file-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'write-file-webpack-plugin/dist/index'>;
}
