module.exports = [
  'react',
  'react-dom',
  'react-router-dom',
  'redux',
  'react-redux',
  'redux-thunk',
  'redux-logger',
  'react-router-redux',
  'axios',
  'styled-components',
  'react-helmet',
  'serialize-javascript',
  'history',
];
